### ISSUE TITLE
Fix failing tests after Clang 11 upgrade

### ISSUE THREAD

**Issue by kkjeer** [microsoft/checkedc-clang#985]
The following tests are currently failing on ADO after upgrading to Clang 11:

* [x] Clang :: Analysis/diagnostics/sarif-multi-diagnostic-test.c (Windows x64 and x86) - fixed by PR #987
* [x] Clang :: CheckedC/generic-function/generic-func-call-info.c (CI Windows Release x86) - fixed by PR #990
* [x] Clang :: CheckedC/verification/codegen-checked.c (CI Windows Release x86) - fixed by PR #989
* [x] Clang :: CheckedC/verification/codegen-unchecked.c (CI Windows Release x86) - fixed by PR #989

**Comment by kkjeer** [comment]
PR #987 fixed the Clang :: Analysis/diagnostics/sarif-multi-diagnostic-test.c failure.

**Comment by kkjeer** [comment]
PR #989 fixed the Clang :: CheckedC/verification/codegen-checked.c and Clang :: CheckedC/verification/codegen-unchecked.c failures.
